name: 'cdc_pipeline'
version: '1.0.0'
config-version: 2
profile: 'cdc_pipeline'
model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]
models:
  cdc_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: incremental
